query and update animals table
ismailakinkunmi/vet_clinic pull request #2
Opened 2022-06-07 20:40 UTC by ismailakinkunmi

- insert data
- use transaction
- write queries to answer questions

2022-06-07 21:14 UTC, keneogu requested changes
Hi @ismailakinkunmi, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Good commit history
- Good PR description

There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media4.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif)

## Required Changes ♻️

- [ ] Your Repo has no scheme.sql, the scheme.sql should contain the new column called `species` with a string type.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-06-07 21:14 UTC, keneogu commented on queries.sql
> +
Inside a transaction, Add

- [ ] `DELETE` all animals born after Jan 1st, 2022 and create a savepoint for the transaction

- [ ]  `UPDATE` all animals' weight to be their weight multiplied by -1. and  Rollback to the savepoint

- [ ] `UPDATE` all animals' weights that are negative to be their weight multiplied by -1. and Commit transaction.

2022-06-07 21:14 UTC, keneogu commented on queries.sql
> +----Who escapes the most, neutered or not neutered animals?
Create a query for who escapes the most, neutered or not neutered animals?

2022-06-07 21:14 UTC, keneogu commented on queries.sql
> +----What is the minimum and maximum weight of each type of animal?
Create a query for the minimum and maximum weight of each type of animal?

2022-06-07 21:14 UTC, keneogu commented on queries.sql
> + ----What is the average number of escape attempts per animal type of those born between 1990 and 2000?
Create a query for this too

2022-06-08 00:51 UTC, omar-labana approved these changes
# **Approved ✔️**

Hi @ismailakinkunmi 

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 05:24 UTC, merged